#!/usr/bin/env python3
"""Generate a deterministic hostile corpus for sharded index readers.

Every generated index is stored beside two valid Safetensors shards. The
survival harness can therefore drive syntactically and semantically accepted
cases through both public index entry points instead of testing only a JSON
parser in isolation.
"""

from __future__ import annotations

import argparse
import json
import random
import re
import struct
from pathlib import Path
from typing import Sequence


MAX_U64 = (1 << 64) - 1
CORPUS_MARKER = ".safetensors-mojo-index-fuzz-corpus"
CORPUS_MARKER_CONTENT = "generated by tools/fuzz/generate_index_corpus.py\n"
VALID_INDEX_NAME = "valid.safetensors.index.json"
CASE_NAME = re.compile(r"case[0-9]+\.safetensors\.index\.json\Z")
GENERATED_DATA_FILES = frozenset(
    {
        "count.txt",
        "shard-a.safetensors",
        "shard-b.safetensors",
        VALID_INDEX_NAME,
    }
)

SPLICE_TOKENS = [
    b'"',
    b"{",
    b"}",
    b"[",
    b"]",
    b",",
    b":",
    b"\\u",
    b"\\ud800",
    b"18446744073709551615",
    b"18446744073709551616",
    b"-1",
    b"1.0",
    b"1e9",
    b"weight_map",
    b"total_size",
    b"../",
    b"\\",
    b"\xff\xfe",
    b"\x00",
    b" " * 9,
]


def compact(value: object) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
    ).encode("utf-8")


def encode_safetensors(header: object, data: bytes = b"") -> bytes:
    encoded = compact(header)
    return struct.pack("<Q", len(encoded)) + encoded + data


def descriptor(
    dtype: str,
    shape: list[int],
    begin: int,
    end: int,
) -> dict[str, object]:
    return {
        "dtype": dtype,
        "shape": shape,
        "data_offsets": [begin, end],
    }


def sharded_tensor_files() -> tuple[bytes, bytes]:
    shard_a = encode_safetensors(
        {"alpha": descriptor("U8", [3], 0, 3)},
        b"\x01\x02\x03",
    )
    shard_b = encode_safetensors(
        {
            "beta": descriptor("I16", [2], 0, 4),
            "empty": descriptor("F32", [0], 4, 4),
        },
        struct.pack("<hh", -2, 300),
    )
    return shard_a, shard_b


def canonical_index() -> bytes:
    return compact(
        {
            "metadata": {"total_size": 7},
            "weight_map": {
                "alpha": "shard-a.safetensors",
                "beta": "shard-b.safetensors",
                "empty": "shard-b.safetensors",
            },
        }
    )


def nested_unknown(depth: int) -> bytes:
    return (
        b'{"future":'
        + (b"[" * depth)
        + b"null"
        + (b"]" * depth)
        + b',"weight_map":{"alpha":"shard-a.safetensors"}}'
    )


def structured_cases() -> list[bytes]:
    """Cover parser, routing, limits, and path-policy boundary shapes."""
    cases = [
        canonical_index(),
        compact(
            {
                "future": [False, {"number": MAX_U64 + 1}],
                "metadata": {
                    "total_size": 7,
                    "total_parameters": 5,
                    "future": {"nested": [True, None, -125.0]},
                },
                "weight_map": {
                    "empty": "shard-b.safetensors",
                    "alpha": "shard-a.safetensors",
                    "beta": "shard-b.safetensors",
                },
            }
        ),
        b" \n\t" + canonical_index() + b"\r ",
        compact(
            {
                "metadata": {"total_size": 3},
                "weight_map": {"alpha": "shard-a.safetensors"},
            }
        ),
        b'{"weight_map":{"alpha":"shard-a.safetensors"}}',
        b'{"metadata":{"total_size":9007199254740993},'
        b'"weight_map":{"alpha":"shard-a.safetensors"}}',
        b'{"metadata":{"total_size":18446744073709551615},'
        b'"weight_map":{"alpha":"shard-a.safetensors"}}',
        b'{"metadata":{"total_size":18446744073709551616},'
        b'"weight_map":{"alpha":"shard-a.safetensors"}}',
        b'{"metadata":{"total_size":1.0},'
        b'"weight_map":{"alpha":"shard-a.safetensors"}}',
        b'{"metadata":{"total_size":1e0},'
        b'"weight_map":{"alpha":"shard-a.safetensors"}}',
        b'{"metadata":{"total_size":-1},'
        b'"weight_map":{"alpha":"shard-a.safetensors"}}',
        b'{"metadata":{"total_size":01},'
        b'"weight_map":{"alpha":"shard-a.safetensors"}}',
        b'{"weight_map":{"alpha":"shard-a.safetensors"},'
        b'"\\u0077eight_map":{"alpha":"shard-a.safetensors"}}',
        b'{"metadata":{"total_size":3,"total_\\u0073ize":3},'
        b'"weight_map":{"alpha":"shard-a.safetensors"}}',
        b'{"weight_map":{"alpha":"shard-a.safetensors",'
        b'"\\u0061lpha":"shard-a.safetensors"}}',
        nested_unknown(128),
        nested_unknown(129),
        b'{"weight_map":{}}',
        b'{"metadata":{"total_size":0}}',
        b'{"metadata":[],"weight_map":{"alpha":"shard-a.safetensors"}}',
        b'{"weight_map":{"alpha":1}}',
        b'{"weight_map":{"alpha":"shard-b.safetensors",'
        b'"beta":"shard-a.safetensors",'
        b'"empty":"shard-b.safetensors"}}',
        b'{"weight_map":{"ghost":"shard-a.safetensors"}}',
        b'{"weight_map":',
        b'{"weight_map":{"\xff":"shard-a.safetensors"}}',
        b'[{"weight_map":{"alpha":"shard-a.safetensors"}}]',
        b'{"weight_map":{"alpha":"shard-a.safetensors"}} null',
    ]

    unsafe_names = [
        "",
        ".",
        "..",
        "../shard-a.safetensors",
        "nested/shard-a.safetensors",
        "nested\\shard-a.safetensors",
        "/tmp/shard-a.safetensors",
        "C:\\shard-a.safetensors",
        "\\\\server\\share.safetensors",
        "https://example.com/shard-a.safetensors",
        "shard:one.safetensors",
        "shard\0.safetensors",
        "shard\n.safetensors",
        "shard-a.bin",
    ]
    for name in unsafe_names:
        cases.append(compact({"weight_map": {"alpha": name}}))
    return cases


def mutate(payload: bytes, rng: random.Random) -> bytes:
    buffer = bytearray(payload)
    if not buffer:
        return bytes(buffer)

    operation = rng.randrange(8)
    if operation == 0:
        index = rng.randrange(len(buffer))
        buffer[index] ^= 1 << rng.randrange(8)
    elif operation == 1:
        buffer[rng.randrange(len(buffer))] = rng.randrange(256)
    elif operation == 2:
        buffer = buffer[: rng.randrange(len(buffer) + 1)]
    elif operation == 3:
        index = rng.randrange(len(buffer) + 1)
        extra = bytes(rng.randrange(256) for _ in range(rng.randrange(1, 9)))
        buffer[index:index] = extra
    elif operation == 4:
        index = rng.randrange(len(buffer) + 1)
        buffer[index:index] = rng.choice(SPLICE_TOKENS)
    elif operation == 5:
        index = rng.randrange(len(buffer))
        del buffer[index : index + rng.randrange(1, 9)]
    elif operation == 6:
        index = rng.randrange(len(buffer))
        length = rng.randrange(1, 33)
        buffer[index:index] = buffer[index : index + length]
    else:
        old = rng.choice(
            [b"weight_map", b"total_size", b"shard-a", b"shard-b"]
        )
        replacement = rng.choice(SPLICE_TOKENS)
        position = bytes(buffer).find(old)
        if position < 0:
            position = rng.randrange(len(buffer))
            buffer[position] ^= 0x80
        else:
            buffer[position : position + len(old)] = replacement
    return bytes(buffer)


def mutational_cases(
    seeds: list[bytes], count: int, rng: random.Random
) -> list[bytes]:
    cases = []
    for _ in range(count):
        payload = rng.choice(seeds)
        for _ in range(rng.randrange(1, 4)):
            payload = mutate(payload, rng)
        cases.append(payload)
    return cases


def nonnegative_int(value: str) -> int:
    parsed = int(value)
    if parsed < 0:
        raise argparse.ArgumentTypeError("value must be nonnegative")
    return parsed


def parse_arguments(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    root = Path(__file__).resolve().parents[2]
    parser.add_argument(
        "--seeds",
        type=Path,
        default=root / "fixtures" / "sharded",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=root / ".pixi" / "fuzz-index-corpus",
    )
    parser.add_argument("--mutations", type=nonnegative_int, default=2000)
    parser.add_argument("--seed", type=int, default=20260825)
    parser.add_argument("--no-structured", action="store_true")
    return parser.parse_args(argv)


def prepare_output_directory(output: Path) -> None:
    """Clear only a corpus directory previously marked as ours."""
    if output.is_symlink():
        raise SystemExit(f"refusing to use a symlink as the output directory: {output}")
    if output.exists() and not output.is_dir():
        raise SystemExit(f"output path is not a directory: {output}")

    output.mkdir(parents=True, exist_ok=True)
    marker = output / CORPUS_MARKER
    entries = list(output.iterdir())
    if entries:
        if marker.is_symlink() or not marker.is_file():
            raise SystemExit(
                f"refusing to replace an unmarked output directory: {output}"
            )
        if marker.read_text(encoding="utf-8") != CORPUS_MARKER_CONTENT:
            raise SystemExit(f"refusing to replace an unknown corpus format: {output}")

    for path in entries:
        if path == marker:
            continue
        if path.name in GENERATED_DATA_FILES or CASE_NAME.fullmatch(path.name):
            if path.is_dir() and not path.is_symlink():
                raise SystemExit(f"generated corpus entry is a directory: {path}")
            path.unlink()
            continue
        raise SystemExit(f"refusing to remove an unexpected corpus entry: {path}")

    marker.write_text(CORPUS_MARKER_CONTENT, encoding="utf-8")


def seed_payloads(seed_root: Path) -> list[bytes]:
    seeds = [
        path.read_bytes()
        for path in sorted(seed_root.rglob("*.safetensors.index.json"))
    ]
    seeds.append(canonical_index())
    return seeds


def main(argv: Sequence[str] | None = None) -> None:
    arguments = parse_arguments(argv)
    seeds = seed_payloads(arguments.seeds)
    rng = random.Random(arguments.seed)
    cases = mutational_cases(seeds, arguments.mutations, rng)
    if not arguments.no_structured:
        cases += structured_cases()

    prepare_output_directory(arguments.output)
    shard_a, shard_b = sharded_tensor_files()
    (arguments.output / "shard-a.safetensors").write_bytes(shard_a)
    (arguments.output / "shard-b.safetensors").write_bytes(shard_b)
    (arguments.output / VALID_INDEX_NAME).write_bytes(canonical_index())
    for index, payload in enumerate(cases):
        name = f"case{index:06d}.safetensors.index.json"
        (arguments.output / name).write_bytes(payload)
    (arguments.output / "count.txt").write_text(
        f"{len(cases)}\n", encoding="utf-8"
    )

    print(
        f"{len(cases)} index cases from {len(seeds)} seeds "
        f"(seed={arguments.seed}, mutations={arguments.mutations}, "
        f"structured={not arguments.no_structured}) -> {arguments.output}"
    )


if __name__ == "__main__":
    main()
