#!/usr/bin/env python3
"""Generate a hostile Safetensors corpus for the Mojo fuzz harness.

Two generators feed one output directory:

* mutational -- random edits of the committed fixtures, including rewrites of
  the declared header length, so most cases stay structurally plausible;
* structured -- hand-shaped cases that walk every dtype, shape boundaries
  near ``2**31``, ``2**32``, ``2**63``, and ``UInt64.MAX``, offset boundaries
  near ``2**63`` and ``UInt64.MAX``, sub-byte element counts around
  ``nbits % 8``, and oversized headers.

The harness only checks that the library survives; it never asserts that a
particular case is accepted or rejected.
"""

from __future__ import annotations

import argparse
import json
import random
import re
import struct
from pathlib import Path
from typing import Sequence


MAX_U64 = (1 << 64) - 1
CORPUS_MARKER = ".safetensors-mojo-fuzz-corpus"
CORPUS_MARKER_CONTENT = "generated by tools/fuzz/generate_corpus.py\n"
CASE_NAME = re.compile(r"case[0-9]+\.bin\Z")

DTYPES = [
    "BOOL", "F4", "F6_E2M3", "F6_E3M2", "U8", "I8",
    "F8_E5M2", "F8_E4M3", "F8_E8M0", "F8_E4M3FNUZ", "F8_E5M2FNUZ",
    "I16", "U16", "F16", "BF16", "I32", "U32", "F32", "C64", "F64", "I64", "U64",
]

EDGE_VALUES = [
    0, 1, 2, 3, 7, 8, 9,
    2**31 - 1, 2**31, 2**32 - 1, 2**32,
    2**63 - 1, 2**63, MAX_U64 - 1, MAX_U64,
]

SPLICE_TOKENS = [
    b'"', b"{", b"}", b"[", b"]", b",", b":", b"\\u", b"\\ud800",
    b"18446744073709551615", b"-1", b"1e9", b"__metadata__",
    b"\xff\xfe", b"\x00", b" " * 9,
]


def encode(header: bytes, data: bytes = b"", declared: int | None = None) -> bytes:
    length = len(header) if declared is None else declared
    return struct.pack("<Q", length) + header + data


def compact(value: object) -> bytes:
    return json.dumps(value, separators=(",", ":")).encode("utf-8")


def descriptor(dtype: str, shape: list[int], begin: int, end: int) -> dict[str, object]:
    return {"dtype": dtype, "shape": shape, "data_offsets": [begin, end]}


def mutate(payload: bytes, rng: random.Random) -> bytes:
    buffer = bytearray(payload)
    if not buffer:
        return bytes(buffer)

    operation = rng.randrange(8)
    if operation == 0:                                      # single bit flip
        index = rng.randrange(len(buffer))
        buffer[index] ^= 1 << rng.randrange(8)
    elif operation == 1:                                    # random byte splat
        buffer[rng.randrange(len(buffer))] = rng.randrange(256)
    elif operation == 2:                                    # truncate
        buffer = buffer[: rng.randrange(len(buffer) + 1)]
    elif operation == 3:                                    # lie about header length
        if len(buffer) >= 8:
            declared = rng.choice([
                0, 1, 7, 8, MAX_U64, 2**63, 100_000_001,
                rng.randrange(2**64), len(buffer) - 8, len(buffer),
            ])
            buffer[0:8] = struct.pack("<Q", declared)
    elif operation == 4:                                    # insert random bytes
        index = rng.randrange(len(buffer) + 1)
        extra = bytes(rng.randrange(256) for _ in range(rng.randrange(1, 9)))
        buffer[index:index] = extra
    elif operation == 5:                                    # splice a JSON token
        index = rng.randrange(len(buffer) + 1)
        buffer[index:index] = rng.choice(SPLICE_TOKENS)
    elif operation == 6:                                    # delete a run
        index = rng.randrange(len(buffer))
        del buffer[index : index + rng.randrange(1, 9)]
    else:                                                   # duplicate a run
        index = rng.randrange(len(buffer))
        length = rng.randrange(1, 17)
        buffer[index:index] = buffer[index : index + length]
    return bytes(buffer)


def mutational_cases(seeds: list[bytes], count: int, rng: random.Random) -> list[bytes]:
    cases = []
    for _ in range(count):
        payload = rng.choice(seeds)
        for _ in range(rng.randrange(1, 4)):
            payload = mutate(payload, rng)
        cases.append(payload)
    return cases


def structured_cases(rng: random.Random) -> list[bytes]:
    cases: list[bytes] = []

    # Every dtype against shape boundaries near 2**31, 2**32, 2**63, and
    # UInt64.MAX, plus offset boundaries near 2**63 and UInt64.MAX.
    for dtype in DTYPES:
        for dimension in EDGE_VALUES:
            for begin, end in [
                (0, 0), (0, 1), (0, MAX_U64), (MAX_U64, 0),
                (1, 0), (0, 2**63), (2**63, MAX_U64),
            ]:
                header = compact({"t": descriptor(dtype, [dimension], begin, end)})
                cases.append(encode(header, b"\x00" * rng.randrange(0, 40)))

    # Several tensors placed adjacent, overlapping, or gapped near the u64 top.
    for _ in range(300):
        tensors: dict[str, object] = {}
        cursor = 0
        for index in range(rng.randrange(1, 6)):
            size = rng.choice([0, 1, 2, 4, 8, 16])
            begin = rng.choice([
                cursor,
                cursor + rng.randrange(-2, 3) if cursor else 0,
                MAX_U64 - size,
                2**63,
            ])
            begin = max(begin, 0)
            end = min(begin + size, MAX_U64)
            tensors[f"t{index}"] = descriptor(rng.choice(DTYPES), [size], begin, end)
            cursor = begin + size
        cases.append(encode(compact(tensors), b"\x11" * rng.randrange(0, 64)))

    # A well-formed header behind a lying length prefix.
    good = compact({"t": descriptor("F32", [2], 0, 8)})
    for declared in [
        0, 1, 7, 8, len(good) - 1, len(good) + 1, len(good) + 8,
        2**31, 2**32, 2**63, MAX_U64, 100_000_000, 100_000_001,
    ]:
        cases.append(encode(good, struct.pack("<ff", 1.5, -2.25), declared=declared))

    # Oversized structures that must not blow the stack or the allocator.
    cases.append(encode(compact({"t": descriptor("U8", [1] * 4096, 0, 1)}), b"\x00"))
    cases.append(encode(compact({"x" * 100_000: descriptor("U8", [1], 0, 1)}), b"\x00"))
    cases.append(encode(
        b'{"t":{"dtype":"U8","shape":[' + b"1," * 50_000 + b'1],"data_offsets":[0,1]}}',
        b"\x00",
    ))
    cases.append(encode(
        b"{"
        + b'"\\u0041":{"dtype":"U8","shape":[0],"data_offsets":[0,0]},' * 2
        + b'"z":{"dtype":"U8","shape":[0],"data_offsets":[0,0]}}'
    ))
    cases.append(encode(b'{"__metadata__":{"k":"' + b"\\ud83d\\ude0a" * 5000 + b'"}}'))
    cases.append(encode(
        b'{"t":{"dtype":"U8","shape":[0],"data_offsets":[0,0]}}' + b" " * 100_000
    ))

    # Sub-byte dtypes at every element count, with both floor and ceiling sizes.
    for dtype, bits in [("F4", 4), ("F6_E2M3", 6), ("F6_E3M2", 6)]:
        for elements in range(25):
            nbits = elements * bits
            for size in sorted({nbits // 8, (nbits + 7) // 8}):
                header = compact({"t": descriptor(dtype, [elements], 0, size)})
                cases.append(encode(header, b"\x5a" * size))

    return cases


def nonnegative_int(value: str) -> int:
    parsed = int(value)
    if parsed < 0:
        raise argparse.ArgumentTypeError("value must be nonnegative")
    return parsed


def parse_arguments(argv: Sequence[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    root = Path(__file__).resolve().parents[2]
    parser.add_argument("--seeds", type=Path, default=root / "fixtures")
    parser.add_argument("--output", type=Path, default=root / ".pixi" / "fuzz-corpus")
    parser.add_argument("--mutations", type=nonnegative_int, default=4000)
    parser.add_argument("--seed", type=int, default=20260825)
    parser.add_argument("--no-structured", action="store_true")
    return parser.parse_args(argv)


def prepare_output_directory(output: Path) -> None:
    """Clears only a corpus directory previously created by this generator."""
    if output.is_symlink():
        raise SystemExit(f"refusing to use a symlink as the output directory: {output}")
    if output.exists() and not output.is_dir():
        raise SystemExit(f"output path is not a directory: {output}")

    output.mkdir(parents=True, exist_ok=True)
    marker = output / CORPUS_MARKER
    entries = list(output.iterdir())
    if entries:
        if marker.is_symlink() or not marker.is_file():
            raise SystemExit(
                "refusing to replace an unmarked output directory: " f"{output}"
            )
        if marker.read_text(encoding="utf-8") != CORPUS_MARKER_CONTENT:
            raise SystemExit(f"refusing to replace an unknown corpus format: {output}")

    for path in entries:
        if path == marker:
            continue
        if path.name == "count.txt" or CASE_NAME.fullmatch(path.name):
            if path.is_dir() and not path.is_symlink():
                raise SystemExit(f"generated corpus entry is a directory: {path}")
            path.unlink()
            continue
        raise SystemExit(f"refusing to remove an unexpected corpus entry: {path}")

    marker.write_text(CORPUS_MARKER_CONTENT, encoding="utf-8")


def main(argv: Sequence[str] | None = None) -> None:
    arguments = parse_arguments(argv)

    seeds = [
        path.read_bytes()
        for path in sorted(arguments.seeds.rglob("*.safetensors"))
    ]
    if not seeds:
        raise SystemExit(f"no seed fixtures found under {arguments.seeds}")

    rng = random.Random(arguments.seed)
    cases = mutational_cases(seeds, arguments.mutations, rng)
    if not arguments.no_structured:
        cases += structured_cases(rng)

    prepare_output_directory(arguments.output)
    for index, payload in enumerate(cases):
        (arguments.output / f"case{index:06d}.bin").write_bytes(payload)
    (arguments.output / "count.txt").write_text(f"{len(cases)}\n", encoding="utf-8")

    structured = not arguments.no_structured
    print(
        f"{len(cases)} cases from {len(seeds)} seeds "
        f"(seed={arguments.seed}, mutations={arguments.mutations}, "
        f"structured={structured}) -> {arguments.output}"
    )


if __name__ == "__main__":
    main()
